# Generated by Django 5.0.7 on 2024-07-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_userbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Charge"),
                    (2, "Purchase"),
                    (4, "Transfer sent"),
                    (3, "Transfer received"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="TransferTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="received_transfers",
                        to="transaction.transaction",
                    ),
                ),
                (
                    "sender_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sent_transfers",
                        to="transaction.transaction",
                    ),
                ),
            ],
        ),
    ]
