# Generated by Django 5.0.7 on 2024-07-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_userscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userscore",
            options={
                "permissions": [("Has_score_permission", "User has Score permission")]
            },
        ),
    ]
