# Generated by Django 5.0.7 on 2024-07-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0005_alter_userscore_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userscore",
            options={
                "permissions": [("Has_score_permission", "Has  Score permission")]
            },
        ),
    ]
