# Generated by Django 5.0.7 on 2024-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
