# Generated by Django 5.0.7 on 2024-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_producttype_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="create_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
