# Generated by Django 5.0.7 on 2024-07-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
