# Generated by Django 5.0.7 on 2024-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.TextField(editable=False),
        ),
    ]
