# Generated by Django 5.0.7 on 2024-08-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_alter_shippingaddress_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.TextField(),
        ),
    ]
